# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install Salesforce CLI
        run: |
         wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
         mkdir sfdx-cli
         tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
         ./sfdx-cli/install

      # Runs a set of commands using the runners shell
      - name: Decrypt KEY
        run: openssl enc -aes-256-cbc -d -in buildfiles/server.key.enc -out server.key -k ${{secrets.DECRYPT_KEY_CI}}
      - name: Convert the VScode Source to metadata API format
        run: 'sfdx force:source:convert -d fsc'
      - name: Authenticate CI
        run: 'sfdx force:auth:jwt:grant --instanceurl https://login.salesforce.com --clentid ${{secrets.CONSUMER_KEY}} --jwtkeyfile server.key --username ${{secrets.USERNAME}} --setdefaultdevusername -a devhub'
      - name: Deploy the code to CI
        run: 'sfdx force:mdapi:deploy --wait 45 --deploydir fsc --targetusername ${{secrets.USERNAME}} --testlevel NotestRun'
          
