# This is a basic workflow to help you get started with Actions

name: MCI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install Salesforce CLI
        run: |
         wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
         mkdir sfdx-cli
         tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
         ./sfdx-cli/install

      # Runs a set of commands using the runners shell
      - name: Decrypt KEY
        run: openssl enc -nosalt -aes-256-cbc -d -in buildfiles/server.key.enc -out server.key -base64 -K ${{secrets.DECRYPT_KEY_CI}} -iv ${{secrets.DECRYPT_KEY_IV}}
      - name: Authenticate CI
        run: 'sfdx force:auth:jwt:grant --instanceurl https://login.salesforce.com --clientid ${{secrets.CONSUMER_KEY}} --jwtkeyfile server.key --username ${{secrets.USERNAME}} --setdefaultdevhubusername  --setalias=hub-org'
      - name: Convert the VScode Source to metadata API format
        run: 'sfdx force:source:convert --rootdir=force-app --outputdir=convert'
      - name: Deploy the code to CI
        run: 'sfdx force:mdapi:deploy --deploydir=convert --testlevel=RunLocalTests --checkonly -u hub-org'
          
